import AppLayout from '@/Layouts/AppLayout';
import Card from '@/Components/Card';
import Input from '@/Components/Input';
import Button from '@/Components/Button';
import { Head, useForm } from '@inertiajs/react';
import { IconClockPause, IconDeviceFloppy } from '@tabler/icons-react';

const defaultData = { work_order_id: '', asset_id: '', downtime_start_at: '', downtime_end_at: '', total_minutes: '', downtime_type: 'full_stop', production_impact_note: '', loss_estimation: '' };

export default function Create({ assets = [], workOrders = [], initialData = defaultData, isEdit = false }) {
    const { data, setData, post, put, errors } = useForm({ ...defaultData, ...initialData, work_order_id: initialData.work_order_id ?? '', asset_id: initialData.asset_id ?? '' });
    const submit = (e) => { e.preventDefault(); isEdit ? put(route('apps.downtime-trackings.update', initialData.id)) : post(route('apps.downtime-trackings.store')); };

    return <><Head title={isEdit ? 'Ubah Downtime' : 'Tambah Downtime'} /><Card title={isEdit ? 'Ubah Downtime' : 'Tambah Downtime'} icon={<IconClockPause size={18} strokeWidth={1.5} />} form={submit} footer={<Button type="submit" icon={<IconDeviceFloppy size={18} strokeWidth={1.5} />} label="Simpan" variant="gray" />}><div className="grid md:grid-cols-2 gap-4 mb-4"><div><label className="text-gray-600 text-sm">Work Order</label><select className="w-full mt-2 px-3 py-2 rounded-md border bg-white dark:bg-gray-900 dark:border-gray-800" value={data.work_order_id} onChange={(e) => setData('work_order_id', e.target.value)}><option value="">- Pilih WO -</option>{workOrders.map((item) => <option key={item.id} value={item.id}>{item.work_order_no}</option>)}</select></div><div><label className="text-gray-600 text-sm">Asset</label><select className="w-full mt-2 px-3 py-2 rounded-md border bg-white dark:bg-gray-900 dark:border-gray-800" value={data.asset_id} onChange={(e) => setData('asset_id', e.target.value)}><option value="">- Pilih Asset -</option>{assets.map((item) => <option key={item.id} value={item.id}>{item.asset_name}</option>)}</select></div><Input label="Downtime Start" type="datetime-local" value={data.downtime_start_at} onChange={(e) => setData('downtime_start_at', e.target.value)} errors={errors.downtime_start_at} /><Input label="Downtime End" type="datetime-local" value={data.downtime_end_at ?? ''} onChange={(e) => setData('downtime_end_at', e.target.value)} errors={errors.downtime_end_at} /><Input label="Total Minutes" type="number" value={data.total_minutes ?? ''} onChange={(e) => setData('total_minutes', e.target.value)} errors={errors.total_minutes} /><Input label="Loss Estimation" type="number" value={data.loss_estimation ?? ''} onChange={(e) => setData('loss_estimation', e.target.value)} errors={errors.loss_estimation} /></div><div className="mb-4"><label className="text-gray-600 text-sm">Downtime Type</label><select className="w-full mt-2 px-3 py-2 rounded-md border bg-white dark:bg-gray-900 dark:border-gray-800" value={data.downtime_type} onChange={(e) => setData('downtime_type', e.target.value)}><option value="full_stop">Full Stop</option><option value="partial_stop">Partial Stop</option><option value="reduced_speed">Reduced Speed</option><option value="standby_loss">Standby Loss</option></select></div><div><label className="text-gray-600 text-sm">Production Impact</label><textarea className="w-full mt-2 px-3 py-2 rounded-md border bg-white dark:bg-gray-900 dark:border-gray-800" rows={3} value={data.production_impact_note ?? ''} onChange={(e) => setData('production_impact_note', e.target.value)} /></div></Card></>;
}

Create.layout = (page) => <AppLayout children={page} />;
