import AppLayout from '@/Layouts/AppLayout';
import Card from '@/Components/Card';
import Input from '@/Components/Input';
import Button from '@/Components/Button';
import { Head, useForm } from '@inertiajs/react';
import { IconDeviceFloppy, IconReportAnalytics } from '@tabler/icons-react';

const defaultData = { report_no: '', report_date: '', shift: 'general', summary: '', downtime_minutes: 0, breakdown_count: 0, pm_compliance: 0, status: 'draft', prepared_by: '' };

export default function Create({ users = [], initialData = defaultData, isEdit = false }) {
    const { data, setData, post, put, errors } = useForm({ ...defaultData, ...initialData, prepared_by: initialData.prepared_by ?? '' });
    const submit = (e) => { e.preventDefault(); isEdit ? put(route('apps.operational-reports.update', initialData.id)) : post(route('apps.operational-reports.store')); };

    return <><Head title={isEdit ? 'Ubah Laporan Operasional' : 'Tambah Laporan Operasional'} /><Card title={isEdit ? 'Ubah Laporan Operasional' : 'Tambah Laporan Operasional'} icon={<IconReportAnalytics size={18} strokeWidth={1.5} />} form={submit} footer={<Button type="submit" icon={<IconDeviceFloppy size={18} strokeWidth={1.5} />} label="Simpan" variant="gray" />}><div className="grid md:grid-cols-2 gap-4 mb-4"><Input label="Report No" type="text" value={data.report_no} onChange={(e) => setData('report_no', e.target.value)} errors={errors.report_no} /><Input label="Report Date" type="date" value={data.report_date} onChange={(e) => setData('report_date', e.target.value)} errors={errors.report_date} /><div><label className="text-gray-600 text-sm">Shift</label><select className="w-full mt-2 px-3 py-2 rounded-md border bg-white dark:bg-gray-900 dark:border-gray-800" value={data.shift} onChange={(e) => setData('shift', e.target.value)}><option value="general">General</option><option value="shift_1">Shift 1</option><option value="shift_2">Shift 2</option><option value="shift_3">Shift 3</option></select></div><div><label className="text-gray-600 text-sm">Prepared By (opsional)</label><select className="w-full mt-2 px-3 py-2 rounded-md border bg-white dark:bg-gray-900 dark:border-gray-800" value={data.prepared_by} onChange={(e) => setData('prepared_by', e.target.value)}><option value="">- Pilih User -</option>{users.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><Input label="Downtime Minutes" type="number" value={data.downtime_minutes} onChange={(e) => setData('downtime_minutes', e.target.value)} errors={errors.downtime_minutes} /><Input label="Breakdown Count" type="number" value={data.breakdown_count} onChange={(e) => setData('breakdown_count', e.target.value)} errors={errors.breakdown_count} /><Input label="PM Compliance (%)" type="number" value={data.pm_compliance} onChange={(e) => setData('pm_compliance', e.target.value)} errors={errors.pm_compliance} /><div><label className="text-gray-600 text-sm">Status</label><select className="w-full mt-2 px-3 py-2 rounded-md border bg-white dark:bg-gray-900 dark:border-gray-800" value={data.status} onChange={(e) => setData('status', e.target.value)}><option value="draft">Draft</option><option value="submitted">Submitted</option><option value="approved">Approved</option></select></div></div><div><label className="text-gray-600 text-sm">Summary</label><textarea className="w-full mt-2 px-3 py-2 rounded-md border bg-white dark:bg-gray-900 dark:border-gray-800" rows={4} value={data.summary} onChange={(e) => setData('summary', e.target.value)} /></div></Card></>;
}

Create.layout = (page) => <AppLayout children={page} />;
